# Generated by Django 4.2.30 on 2026-09-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this material category')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in menus and filters')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Apex Sand & Aggregates', max_length=150)),
                ('tagline', models.CharField(default='Quality sand and aggregates for stronger construction', max_length=255)),
                ('phone_display', models.CharField(default='+91 98765 43210', max_length=30)),
                ('phone_raw', models.CharField(default='+919876543210', help_text='Digits with country code, no spaces for tel: link', max_length=30)),
                ('whatsapp_number', models.CharField(default='919876543210', help_text='Digits only with country code (e.g. 919876543210) for wa.me links', max_length=30)),
                ('email', models.EmailField(default='info@apexaggregates.com', max_length=254)),
                ('address', models.CharField(default='Plot 45, Highway Industrial Area, Gujarat, India', max_length=255)),
                ('business_hours', models.CharField(default='Mon - Sat: 8:00 AM - 7:00 PM', max_length=100)),
                ('google_maps_url', models.URLField(default='https://www.google.com/maps?q=Gujarat,India&output=embed', max_length=500)),
                ('whatsapp_default_message', models.TextField(default='Hello, I am interested in your sand and aggregates products. I would like to know the price and availability.')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
            ],
            options={
                'verbose_name': 'Business Configuration & Contact Settings',
                'verbose_name_plural': 'Business Configuration & Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload high quality product photo', null=True, upload_to='products/')),
                ('short_description', models.CharField(help_text='Short one-line summary displayed on product cards', max_length=255)),
                ('description', models.TextField(help_text='Detailed specification, uses, grading, and material properties')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit in INR (₹)', max_digits=10)),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Truck', 'Truck (Full Load)'), ('Cubic Meter', 'Cubic Meter (m³)'), ('Brass', 'Brass'), ('Bag', 'Bag (50 kg)')], default='Ton', max_length=50)),
                ('available', models.BooleanField(default=True, help_text='Is this material currently in stock and available for delivery?')),
                ('featured', models.BooleanField(default=False, help_text='Display prominently on the homepage products showcase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='website.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(help_text='Delivery site address, landmark, or location')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantity in product units', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, editable=False, help_text='Unit price snapshot at order submission', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Calculated: price * quantity', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending (New)'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing / Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special delivery instructions, timing, or dump truck access notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='website.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company or builder firm', max_length=150)),
                ('product_name', models.CharField(blank=True, help_text='Product or material name', max_length=150)),
                ('quantity', models.CharField(blank=True, help_text='Requested quantity', max_length=50)),
                ('unit', models.CharField(blank=True, help_text='e.g. Ton, Truck, Brass', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Delivery destination', max_length=255)),
                ('message', models.TextField(help_text='Specific requirements, quality grading, or site timeline')),
                ('status', models.CharField(choices=[('New', 'New Enquiry'), ('Contacted', 'Contacted / Quotation Sent'), ('Closed', 'Closed / Converted')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='website.product')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
