# Generated by Django 4.2.30 on 2026-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='Ahmedabad, Gujarat, India', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='business_hours',
            field=models.CharField(default='Open 24 hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='business_name',
            field=models.CharField(default='LJ ENTERPRISE', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='infoljenterprise07@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_url',
            field=models.URLField(default='https://www.google.com/maps?q=Ahmedabad,Gujarat,India&output=embed', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/infoljenterprise?stkn=MWd3cGN3dDV6Ym44aA=='),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/company/rashienterprise'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_display',
            field=models.CharField(default='+91 81413 52886', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_raw',
            field=models.CharField(default='+918141352886', help_text='Digits with country code, no spaces for tel: link', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(default='At the heart of every strong structure lies a solid foundation — and that starts with quality materials.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_default_message',
            field=models.TextField(default='Hello LJ Enterprise, I am interested in your sand, GSB, and aggregates materials. Please share pricing and availability.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(default='918141352886', help_text='Digits only with country code (e.g. 918141352886) for wa.me links', max_length=30),
        ),
    ]
